/**
 * Game Of Life API
 * The game of life api that allows you to compute the next state of some population.  ### Check out its features:  * Send the state of the game to evaluate 🧬 * Send query to change number of replicas 📈 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameOfLifeApi);
  }
}(this, function(expect, GameOfLifeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameOfLifeApi.MapInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MapInner', function() {
    it('should create an instance of MapInner', function() {
      // uncomment below and update the code to test MapInner
      //var instance = new GameOfLifeApi.MapInner();
      //expect(instance).to.be.a(GameOfLifeApi.MapInner);
    });

    it('should have the property rowIndex (base name: "rowIndex")', function() {
      // uncomment below and update the code to test the property rowIndex
      //var instance = new GameOfLifeApi.MapInner();
      //expect(instance).to.be();
    });

    it('should have the property columnIndex (base name: "columnIndex")', function() {
      // uncomment below and update the code to test the property columnIndex
      //var instance = new GameOfLifeApi.MapInner();
      //expect(instance).to.be();
    });

    it('should have the property isAlive (base name: "isAlive")', function() {
      // uncomment below and update the code to test the property isAlive
      //var instance = new GameOfLifeApi.MapInner();
      //expect(instance).to.be();
    });

  });

}));
