/**
 * Game Of Life API
 * The game of life api that allows you to compute the next state of some population.  ### Check out its features:  * Send the state of the game to evaluate 🧬 * Send query to change number of replicas 📈 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MapInner from '../model/MapInner';

/**
* Logic service.
* @module api/LogicApi
* @version 1.0.0
*/
export default class LogicApi {

    /**
    * Constructs a new LogicApi. 
    * @alias module:api/LogicApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the nextGen operation.
     * @callback module:api/LogicApi~nextGenCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/MapInner>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Evaluates next generation
     * By given map evaluates next generation in game of life.
     * @param {Array.<module:model/MapInner>} mapInner Evaluate next generation
     * @param {module:api/LogicApi~nextGenCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/MapInner>}
     */
    nextGen(mapInner, callback) {
      let postBody = mapInner;
      // verify the required parameter 'mapInner' is set
      if (mapInner === undefined || mapInner === null) {
        throw new Error("Missing the required parameter 'mapInner' when calling nextGen");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [MapInner];
      return this.apiClient.callApi(
        '/evaluateNextGeneration', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
