/**
 * Game Of Life API
 * The game of life api that allows you to compute the next state of some population.  ### Check out its features:  * Send the state of the game to evaluate 🧬 * Send query to change number of replicas 📈 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MapInner model module.
 * @module model/MapInner
 * @version 1.0.0
 */
class MapInner {
    /**
     * Constructs a new <code>MapInner</code>.
     * @alias module:model/MapInner
     */
    constructor() { 
        
        MapInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MapInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MapInner} obj Optional instance to populate.
     * @return {module:model/MapInner} The populated <code>MapInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MapInner();

            if (data.hasOwnProperty('rowIndex')) {
                obj['rowIndex'] = ApiClient.convertToType(data['rowIndex'], 'Number');
            }
            if (data.hasOwnProperty('columnIndex')) {
                obj['columnIndex'] = ApiClient.convertToType(data['columnIndex'], 'Number');
            }
            if (data.hasOwnProperty('isAlive')) {
                obj['isAlive'] = ApiClient.convertToType(data['isAlive'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MapInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MapInner</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} rowIndex
 */
MapInner.prototype['rowIndex'] = undefined;

/**
 * @member {Number} columnIndex
 */
MapInner.prototype['columnIndex'] = undefined;

/**
 * @member {Boolean} isAlive
 */
MapInner.prototype['isAlive'] = undefined;






export default MapInner;

