/*
 * Game Of Life API
 *
 * The game of life api that allows you to compute the next state of some population.  ### Check out its features:  * Send the state of the game to evaluate 🧬 * Send query to change number of replicas 📈 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MapInner struct {

	RowIndex int32 `json:"rowIndex,omitempty"`

	ColumnIndex int32 `json:"columnIndex,omitempty"`

	IsAlive bool `json:"isAlive,omitempty"`
}
